services:
  # jupyter:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./notebooks:/home/jovyan/notebooks
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
